apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sort-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sort-app
  template:
    metadata:
      labels:
        app: java-sort-app
    spec:
      containers:
      - name: java-sort-app
        image: localhost:5000/java-sort-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80